# Generated by Django 3.2.9 on 2021-11-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo_habitacion',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
